### ISSUE TITLE
unicode install error

### ISSUE THREAD

**Issue by s2zaman** [dodo/node-unicodetable#6]
I get the following error on `npm install unicode`
I came across with this while installing `docpad-plugin-minicms` and it is a dependency there.

```
npm http GET http://registry.npmjs.org/unicode
npm http 304 http://registry.npmjs.org/unicode

> unicode@0.4.4 postinstall d:\docmini\node_modules\unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
Warning: using slow naiv Buffer.indexOf function!
`npm install buffertools` to speed things up.
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by jmjsdev** [comment]
I had the same error and unicode is the only module that failed with our corporate proxy, I have tests the code of install.js and I have resolved the problem by replacing this code : 

``` javascript
unicodedatafile = {
    host: "unicode.org",
```

By this code : 

``` javascript
unicodedatafile = {
    host: "http://unicode.org",
```

**Comment by ihr** [comment]
I'm running CentOS 7 and fixed the issue by doing the following:
1. sudo yum install unicode-ucd
2. sudo ln -s /usr/share/unicode/ucd/UnicodeData.txt /usr/share/unicode/UnicodeData.txt
3. rm -rf node_modules/slug/ node_modules/unicode/
4. npm install slug

**Comment by lutaoact** [comment]
this worked for me!

download `UnicodeData.txt` by yourself, and then put it in the directory which is the same with `install.js`
then run `node install.js` again.
